#!/bin/sh
#
# @name Gazebo Starling2
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=baylands}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=starling_v2}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.0625
param set-default CA_ROTOR0_PY 0.0850
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.0625
param set-default CA_ROTOR1_PY -0.0850
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 0.0625
param set-default CA_ROTOR2_PY -0.0850
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.0625
param set-default CA_ROTOR3_PY 0.0850
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 100
param set-default SIM_GZ_EC_MIN2 100
param set-default SIM_GZ_EC_MIN3 100
param set-default SIM_GZ_EC_MIN4 100

param set-default SIM_GZ_EC_MAX1 2320
param set-default SIM_GZ_EC_MAX2 2320
param set-default SIM_GZ_EC_MAX3 2320
param set-default SIM_GZ_EC_MAX4 2320

param set-default MPC_THR_HOVER 0.34
param set-default NAV_DLL_ACT 2
param set-default THR_MDL_FAC 0.9
param set-default MPC_THR_MAX 0.60
param set-default MPC_THR_MIN 0.07
param set-default MPC_MANTHR_MIN 0.07

# Attitude controller gains
param set-default MC_ROLLRATE_K	1.0
param set-default MC_PITCHRATE_K	1.0
param set-default MC_YAWRATE_K	1.0
param set-default MC_ROLL_CUTOFF	30.0
param set-default MC_PITCH_CUTOFF	30.0
param set-default MC_YAW_CUTOFF	10.0

param set-default MC_ROLL_P	16.0
param set-default MC_ROLLRATE_P	0.072
param set-default MC_ROLLRATE_I	0.171
param set-default MC_ROLLRATE_D	0.0009

param set-default MC_PITCH_P	16.0
param set-default MC_PITCHRATE_P	0.097
param set-default MC_PITCHRATE_I	0.228
param set-default MC_PITCHRATE_D	0.0011

param set-default MC_YAW_P	2.8
param set-default MC_YAWRATE_P	0.15
param set-default MC_YAWRATE_I	0.5
param set-default MC_YAWRATE_D	0.0
param set-default MC_ROLLRATE_MAX	130.0
param set-default MC_PITCHRATE_MAX 130.0
param set-default MC_YAWRATE_MAX	150.0

# Noise management
param set-default MOT_SLEW_MAX	0.0
param set-default IMU_DGYRO_CUTOFF	60.0
param set-default IMU_ACCEL_CUTOFF	80.0
param set-default IMU_GYRO_CUTOFF	80.0
param set-default IMU_GYRO_DNF_EN 1
param set-default IMU_GYRO_DNF_HMC 3
param set-default IMU_GYRO_DNF_BW 15

# Takeoff and landing
param set-default MPC_TKO_RAMP_T	1.00
param set-default COM_SPOOLUP_TIME	2.0
param set-default MPC_TKO_SPEED	1.50
param set-default LNDMC_ROT_MAX	30.0
param set-default LNDMC_TRIG_TIME	0.5
param set-default COM_DISARM_LAND	0.1

param set-default COM_DISARM_PRFLT -1