#!/bin/sh
#
# @name Gazebo Starling2 (mocap / external-vision localization)
#
# @type Quadrotor
#
# Copy of 4080_gz_starling_v2 with GPS/mag simulation disabled and EKF2
# configured to fuse external vision (mocap_px4_bridge -> /fmu/in/vehicle_visual_odometry).

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=baylands}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=starling_v2_notune}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 0
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 0

# External-vision-only localization (no GPS, no mag, no baro).
# Keep EKF2_HGT_REF before EKF2_GPS_CTRL: PX4 resets GPS_CTRL when the height
# reference still points at GPS.
param set-default SYS_HAS_GPS 0
param set-default SYS_HAS_MAG 0
param set-default EKF2_MAG_TYPE 5
param set-default COM_ARM_WO_GPS 1
param set-default EKF2_HGT_REF 3
param set-default EKF2_GPS_CTRL 0
param set-default EKF2_BARO_CTRL 0
param set-default EKF2_RNG_CTRL 0
param set-default EKF2_OF_CTRL 0
param set-default EKF2_EV_CTRL 11
param set-default EKF2_EV_QMIN 0
param set-default EKF2_EV_NOISE_MD 0
param set-default EKF2_EVP_NOISE 0.02
param set-default EKF2_EVA_NOISE 0.05
param set-default EKF2_EVV_NOISE 0.1
param set-default EKF2_EVP_GATE 5
param set-default EKF2_EVV_GATE 3
param set-default EKF2_EV_DELAY 0
param set-default EKF2_NOAID_TOUT 1000000

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.085
param set-default CA_ROTOR0_PY 0.0625
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.085
param set-default CA_ROTOR1_PY -0.0625
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 0.085
param set-default CA_ROTOR2_PY -0.0625
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.085
param set-default CA_ROTOR3_PY 0.0625
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

param set-default MPC_THR_HOVER 0.60
param set-default NAV_DLL_ACT 2

param set-default COM_DISARM_PRFLT -1
